# 区块链网络 Docker Compose 配置

version: '2'

services:
  # 排序节点
  orderer.icbc.com:
    container_name: orderer.icbc.com
    image: hyperledger/fabric-orderer:2.2
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/icbc.com/orderers/orderer.icbc.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/icbc.com/orderers/orderer.icbc.com/tls/:/var/hyperledger/orderer/tls
      - orderer.icbc.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - icbc-collectible-network

  # ICBC 组织的对等节点 0
  peer0.icbc.com:
    container_name: peer0.icbc.com
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.icbc.com
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
      - CORE_PEER_LOCALMSPID=ICBCMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.icbc.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=icbc-collectible-network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.icbc.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.icbc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.icbc.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/icbc.com/peers/peer0.icbc.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/icbc.com/peers/peer0.icbc.com/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/icbc.com/users/Admin@icbc.com/msp:/etc/hyperledger/fabric/admin/msp
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./channel-artifacts:/etc/hyperledger/fabric/channel
      - ../chaincode:/opt/gopath/src/github.com/chaincode
      - peer0.icbc.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.icbc.com
      - couchdb0.icbc.com
    networks:
      - icbc-collectible-network

  # ICBC 组织的对等节点 1
  peer1.icbc.com:
    container_name: peer1.icbc.com
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.icbc.com
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
      - CORE_PEER_LOCALMSPID=ICBCMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer1.icbc.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=icbc-collectible-network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.icbc.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.icbc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.icbc.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/icbc.com/peers/peer1.icbc.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/icbc.com/peers/peer1.icbc.com/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/icbc.com/users/Admin@icbc.com/msp:/etc/hyperledger/fabric/admin/msp
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./channel-artifacts:/etc/hyperledger/fabric/channel
      - ../chaincode:/opt/gopath/src/github.com/chaincode
      - peer1.icbc.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer.icbc.com
      - couchdb1.icbc.com
    networks:
      - icbc-collectible-network

  # BrandA 组织的对等节点
  peer0.branda.com:
    container_name: peer0.branda.com
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.branda.com
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
      - CORE_PEER_LOCALMSPID=BrandAMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.branda.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=icbc-collectible-network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.branda.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.branda.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.branda.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/branda.com/peers/peer0.branda.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/branda.com/peers/peer0.branda.com/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/branda.com/users/Admin@branda.com/msp:/etc/hyperledger/fabric/admin/msp
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./channel-artifacts:/etc/hyperledger/fabric/channel
      - ../chaincode:/opt/gopath/src/github.com/chaincode
      - peer0.branda.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer.icbc.com
      - couchdb0.branda.com
    networks:
      - icbc-collectible-network

  # BrandB 组织的对等节点
  peer0.brandb.com:
    container_name: peer0.brandb.com
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.brandb.com
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
      - CORE_PEER_LOCALMSPID=BrandBMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ADDRESS=peer0.brandb.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=icbc-collectible-network
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.brandb.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.brandb.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.brandb.com:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/brandb.com/peers/peer0.brandb.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/brandb.com/peers/peer0.brandb.com/tls:/etc/hyperledger/fabric/tls
      - ./crypto-config/peerOrganizations/brandb.com/users/Admin@brandb.com/msp:/etc/hyperledger/fabric/admin/msp
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./channel-artifacts:/etc/hyperledger/fabric/channel
      - ../chaincode:/opt/gopath/src/github.com/chaincode
      - peer0.brandb.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
    depends_on:
      - orderer.icbc.com
      - couchdb0.brandb.com
    networks:
      - icbc-collectible-network

  # ICBC 组织的 CA 节点
  ca.icbc.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.icbc.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.icbc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/icbc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.icbc.com
    networks:
      - icbc-collectible-network

  # BrandA 组织的 CA 节点
  ca.branda.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.branda.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.branda.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - 8054:8054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/branda.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.branda.com
    networks:
      - icbc-collectible-network

  # BrandB 组织的 CA 节点
  ca.brandb.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.brandb.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.brandb.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - 9054:9054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/brandb.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.brandb.com
    networks:
      - icbc-collectible-network

  # ICBC 组织的 CouchDB 节点 0
  couchdb0.icbc.com:
    container_name: couchdb0.icbc.com
    image: hyperledger/fabric-couchdb:0.4.22
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    volumes:
      - couchdb0.icbc.com:/opt/couchdb/data
    networks:
      - icbc-collectible-network

  # ICBC 组织的 CouchDB 节点 1
  couchdb1.icbc.com:
    container_name: couchdb1.icbc.com
    image: hyperledger/fabric-couchdb:0.4.22
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    volumes:
      - couchdb1.icbc.com:/opt/couchdb/data
    networks:
      - icbc-collectible-network

  # BrandA 组织的 CouchDB 节点
  couchdb0.branda.com:
    container_name: couchdb0.branda.com
    image: hyperledger/fabric-couchdb:0.4.22
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7984:5984
    volumes:
      - couchdb0.branda.com:/opt/couchdb/data
    networks:
      - icbc-collectible-network

  # BrandB 组织的 CouchDB 节点
  couchdb0.brandb.com:
    container_name: couchdb0.brandb.com
    image: hyperledger/fabric-couchdb:0.4.22
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 8984:5984
    volumes:
      - couchdb0.brandb.com:/opt/couchdb/data
    networks:
      - icbc-collectible-network

  # 命令行工具容器
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.2
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=syschannel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.icbc.com:7051
      - CORE_PEER_LOCALMSPID=ICBCMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/icbc.com/users/Admin@icbc.com/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/icbc.com/peers/peer0.icbc.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/icbc.com/peers/peer0.icbc.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/icbc.com/peers/peer0.icbc.com/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - icbc-collectible-network
    depends_on:
      - orderer.icbc.com
      - peer0.icbc.com
      - peer1.icbc.com
      - peer0.branda.com
      - peer0.brandb.com
      - couchdb0.icbc.com
      - couchdb1.icbc.com
      - couchdb0.branda.com
      - couchdb0.brandb.com

# 网络定义
networks:
  icbc-collectible-network:
    name: icbc-collectible-network
    external: true

# 卷定义
volumes:
  orderer.icbc.com:
  peer0.icbc.com:
  peer1.icbc.com:
  peer0.branda.com:
  peer0.brandb.com:
  couchdb0.icbc.com:
  couchdb1.icbc.com:
  couchdb0.branda.com:
  couchdb0.brandb.com: